dist: xenial
language: java
jdk:
  - openjdk8

install:
  - mvn -N io.takari:maven:wrapper -Dmaven=3.6.0
  - java -version && javac -version && ./mvnw -version -B

before_script:
  # Check each method has docs and tests, if missing, fail
  - bash .travis/check-missing.sh

script:
  - ./mvnw clean install -B

cache:
  directories:
    - $HOME/.m2